development:
  adapter: postgresql
  encoding: unicode
  database: indiemusic-dev
  pool: 5
  username: kmklapak
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: indiemusic-test
  pool: 5
  username: kmklapak
  password: 
